config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'messages/create'
  resources :municips
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/municip.rb
class Municip < ApplicationRecord
end

app/models/municipe.rb
class Municipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.fetch(:article, {})
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    flash[:notice] = params[:notice]
  end
 
  def create
    SendSMS.new(params[:message], params[:number]).call
    redirect_to(action: 'new', notice: 'SMS enviado o/')
  end
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
end

app/controllers/municips_controller.rb
class MunicipsController < ApplicationController
  before_action :set_municip, only: %i[ show edit update destroy ]

  # GET /municips or /municips.json
  def index
    @municips = Municip.all
  end

  # GET /municips/1 or /municips/1.json
  def show
  end

  # GET /municips/new
  def new
    @municip = Municip.new
  end

  # GET /municips/1/edit
  def edit
  end

  # POST /municips or /municips.json
  def create
    @municip = Municip.new(municip_params)

    respond_to do |format|
      if @municip.save
        format.html { redirect_to municip_url(@municip), notice: "Municip was successfully created." }
        format.json { render :show, status: :created, location: @municip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municips/1 or /municips/1.json
  def update
    respond_to do |format|
      if @municip.update(municip_params) 		
	  
		UserNotifier.send_signup_email(@user).deliver
        format.html { redirect_to municip_url(@municip), notice: "Municip was successfully updated." }
        format.json { render :show, status: :ok, location: @municip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municips/1 or /municips/1.json
  def destroy
    @municip.destroy

    respond_to do |format|
      format.html { redirect_to municips_url, notice: "Municip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municip
      @municip = Municip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municip_params
      params.require(:municip).permit(:nome, :cpf, :cns, :emailmunicipe, :data, :nascimento, :telefone, :foto, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/helpers/municips_helper.rb
module MunicipsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Municipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/new.html.erb
<h3>Enviand SMS</h3>
​
<hr>
​
<%= form_with(url: 'messages', remote: false) do |form| %>
  Mensagem: <%= form.text_area :message %><br><br>
  Número: <%= form.text_field :number %><br><br>
  <%= form.submit 'Enviar SMS' %>
<% end %>
​
<hr>
​
<% if flash[:notice] %>
  <div><%= flash[:notice] %></div>
<% end %>

app/views/municipes/show.html.erb
<html>
<head>
         <title></title>
</head>
<body>
         <p>
                   <b>Nome:</b> <%= @municipes.nome %>
         </p>
         <p>
                   <b>CPF:</b> <%= @municipes.cpf %>
         </p>
         <p>
                   <b>CNS:</b> <%= @municipes.cns %>
         </p>
         <p>
                   <b>Email:</b> <%= @municipes.emailmunicipe %>
         </p>
         <p>
                   <b>Data Nascimento:</b><%= @municipes.nascimento %>
         </p>
	 <p>
                   <b>Data Cadastro:</b> <%= @municipes.data %>
         </p>
</body>
</html>

app/views/municips/_form.html.erb
<%= form_with(model: municip) do |form| %>
  <% if municip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(municip.errors.count, "error") %> prohibited this municip from being saved:</h2>

      <ul>
        <% municip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :cns, style: "display: block" %>
    <%= form.text_field :cns %>
  </div>

  <div>
    <%= form.label :emailmunicipe, style: "display: block" %>
    <%= form.text_field :emailmunicipe %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :nascimento, style: "display: block" %>
    <%= form.date_field :nascimento %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :foto, style: "display: block" %>
    <%= form.text_field :foto %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/municips/_municip.html.erb
<div id="<%= dom_id municip %>">
  <p>
    <strong>Nome:</strong>
    <%= municip.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= municip.cpf %>
  </p>

  <p>
    <strong>Cns:</strong>
    <%= municip.cns %>
  </p>

  <p>
    <strong>Emailmunicipe:</strong>
    <%= municip.emailmunicipe %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= municip.data %>
  </p>

  <p>
    <strong>Nascimento:</strong>
    <%= municip.nascimento %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= municip.telefone %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= municip.foto %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= municip.status %>
  </p>

</div>

app/views/municips/edit.html.erb
<h1>Editing municip</h1>

<%= render "form", municip: @municip %>

<br>

<div>
  <%= link_to "Show this municip", @municip %> |
  <%= link_to "Back to municips", municips_path %>
</div>

app/views/municips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Municipes</h1>

<div id="municips">
  <% @municips.each do |municip| %>
    <%= render municip %>
    <p>
      <%= link_to "Show this municip", municip %>
    </p>
  <% end %>
</div>

<%= link_to "New municip", new_municip_path %>

app/views/municips/new.html.erb
<h1>New municip</h1>

<%= render "form", municip: @municip %>

<br>

<div>
  <%= link_to "Back to municips", municips_path %>
</div>

app/views/municips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @municip %>

<div>
  <%= link_to "Edit this municip", edit_municip_path(@municip) %> |
  <%= link_to "Back to municips", municips_path %>

</div>